### ISSUE TITLE
>10 sub items - only first 10 are shown

### ISSUE THREAD

**Issue by skizzo** [renrizzolo/react-native-sectioned-multi-select#124] opened 2019-07-18 15:11 UTC
Hi,
I can't get my head around this. Whatever I do, if an item contains more than 10 sub items, only the first 10 sub items are displayed. So, my `items` look like this:

```
items = [{
  id: 0,
  key: "root",
  name: "Currency",
  children: [
    {id: 1, name: "Currency 1"},
    {id: 2, name: "Currency 2"},
    {id: 3, name: "Currency 3"},
    {id: 4, name: "Currency 4"},
    {id: 5, name: "Currency 5"},
    {id: 6, name: "Currency 6"},
    {id: 7, name: "Currency 7"},
    {id: 8, name: "Currency 8"},
    {id: 9, name: "Currency 9"},
    {id: 10, name: "Currency 10"},
    {id: 11, name: "Currency 11"}, // <- not shown
    {id: 12, name: "Currency 12"}, // <- not shown either
  ]
}]
```

My `SectionedMultiSelect` like this:

```
<SectionedMultiSelect
  ref={obj => this.multiSelects[selectKey] = obj}
  items={items}
  uniqueKey={"id"}
  subKey={"children"}
  showDropDowns={false}
  />
```

And the result:
![Screenshot 2019-07-18 at 17 10 19](https://user-images.githubusercontent.com/2892572/61469117-f309f400-a97e-11e9-837e-6eff1fb75c4a.png)

What am I doing wrong here? Thanks!

**Comment by renrizzolo** [comment] 2019-07-19 03:05
I can't remember if there was a prop added for it but it's probably `initialItemsToRender` prop of the FlatList.
(You can't scroll down enough to start rendering the new items)

To test this, try duplicating your parent object, when you scroll down it should show them all.

**Comment by jonathanmachado** [comment] 2019-07-31 14:44
@renrizzolo I have same problem what it's your solution? I don't see initalItemsToRender prop

**Comment by skizzo** [comment] 2019-07-31 17:38
You need to add the property yourself. Maybe that's something to consider for the next version of this package, there seem to be people who actually need to show more than 10 items :D

**Comment by jonathanmachado** [comment] 2019-07-31 17:54
@skizzo  I'm trying to add an example 20 but it still doesn't work, would you help me with an example?

I add

                  initialNumToRender={20}
                  initialItemsToRender={20}
                  removeClippedSubviews={false}


but I have not been lucky

**Comment by jonathanmachado** [comment] 2019-07-31 19:12
I found the problem and create [PR](https://github.com/renrizzolo/react-native-sectioned-multi-select/pull/127), please see it's the best solution because the problem is FlatList doesn't render all properties.  Thanks and Regards

**Comment by renrizzolo** [comment] 2019-08-01 06:17
I'm not able to reproduce this with the example app.
All of the items are always shown (on iOS simulator).

**Comment by renrizzolo** [comment] 2019-08-01 06:52
Thanks, to make it more open to furhter customization I've added `itemsFlatListProps` and `subItemsFlatListProps`. These are both objects that are spread onto the corresponding FlatLists.
I also added the default for the sub items' FlatList `InitialNumToRender` to be 20 so you should just be able to update and it should fix the issue you're having. As I said above I couldn't replicate it but if changing the number fixes it for you, it should be fixed in the update.

#### usage:
```js
<SectionedMultiSelect
 ...
 subItemsFlatListProps={{initialNumToRender: 15, [any other prop you want to add or override]}}
/>
```

**Closed as completed by renrizzolo** 2019-08-01 06:52 UTC

**Comment by jonathanmachado** [comment] 2019-08-01 12:30
thanks @renrizzolo
